Universidad del Valle

Facultad de Ingeniería | Escuela de Ingeniería de Sistemas y Computación | Inteligencia Artificial

Sebastián Tutistar Valencia - 2110309 | Carlos Alberto Henao - 2110339 | Oscar Trujillo - 2110318

Árboles de Decisión

In [1]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Importamos las bibliotecas necesarias para desarrollar el lab.

import numpy as np
import pandas as pd
import sklearn
import warnings

1. Leer el archivo stroke.csv.

In [2]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Url y cargue de los datos

url= ("https://raw.githubusercontent.com/xlPlanetarizaGol/Machine_Learning_IA/main/stroke.csv")
datos = pd.read_csv(url, sep=",")
datos

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
695,Female,29.0,0,0,Yes,Private,Rural,91.45,24.2,never smoked,0
696,Female,12.0,0,0,No,children,Rural,90.58,19.2,Unknown,0
697,Female,37.0,0,0,Yes,Private,Urban,91.45,25.8,Unknown,0
698,Female,30.0,0,0,Yes,Private,Rural,89.63,23.2,smokes,0
699,Female,59.0,0,0,Yes,Govt_job,Rural,86.39,30.2,never smoked,0

In [3]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Resumen de la información

datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             700 non-null    object
 1   age                700 non-null    float64
 2   hypertension       700 non-null    int64
 3   heart_disease      700 non-null    int64
 4   ever_married       700 non-null    object
 5   work_type          700 non-null    object
 6   Residence_type     700 non-null    object
 7   avg_glucose_level  700 non-null    float64
 8   bmi                651 non-null    float64
 9   smoking_status     700 non-null    object
 10  stroke             700 non-null    int64
dtypes: float64(3), int64(3), object(5)
memory usage: 60.3+ KB

2. Seleccionar aleatoriamente el 80% del conjunto de datos para entrenar y el 20% restante para las pruebas.

In [4]:
from sklearn.model_selection import train_test_split 

N=len(datos)
cTrain=int(N*0.8)
cTest=N-cTrain 

print(N,cTrain,cTest)

train_data,test_data= sklearn.model_selection.train_test_split(datos, train_size=cTrain, test_size=cTest)

700 560 140

In [5]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Clasificación, datos de entrenamiento

train_data.shape

(560, 11)

Observamos que los datos de entrenamientos son 560 observaciones y 11 variables.

In [6]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Imprimir 5 filas de datos del entrenamiento

train_data.head(5)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
379,Female,53.0,0,0,Yes,Private,Rural,68.76,35.6,formerly smoked,0
245,Female,14.0,0,0,No,children,Rural,57.93,30.9,Unknown,1
624,Male,65.0,0,1,Yes,Self-employed,Urban,58.37,28.0,smokes,0
57,Male,78.0,0,0,Yes,Private,Urban,237.75,NaN,formerly smoked,1
543,Female,57.0,0,0,Yes,Self-employed,Urban,98.44,33.6,Unknown,0

In [7]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Estadística descriptiva acerca de los datos de entrenamiento

train_data.describe()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,560.000000,560.000000,560.000000,560.000000,525.000000,560.000000
mean,50.461500,0.141071,0.096429,114.525357,29.687238,0.332143
std,22.295588,0.348406,0.295442,51.926143,7.758940,0.471403
min,0.320000,0.000000,0.000000,55.250000,12.000000,0.000000
25%,34.000000,0.000000,0.000000,77.992500,24.400000,0.000000
50%,54.000000,0.000000,0.000000,95.110000,28.400000,0.000000
75%,69.250000,0.000000,0.000000,130.070000,34.100000,1.000000
max,82.000000,1.000000,1.000000,271.740000,60.900000,1.000000

3. Utilizar una estrategia para normalizar los datos y llenar los datos faltantes.

In [8]:
#Pipeline | atributos númericos.

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import MinMaxScaler

# Variables númericas, en total 3

num_attribs = ['age','avg_glucose_level', 'bmi']
num_pipeline = Pipeline([("imputer", SimpleImputer(strategy="median")),
                         ("scaler", StandardScaler())])

In [9]:
#Pipeline | atributos categóricos.

from sklearn.preprocessing import OneHotEncoder 
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Variables Categóricas, en total 7.
cat_attribs = ['gender','hypertension','heart_disease','ever_married','work_type','Residence_type','smoking_status']

cat_pipeline = Pipeline([
("imputer", SimpleImputer(strategy="most_frequent")), 
("cat_encoder", OneHotEncoder(sparse=False))
])

In [10]:
#Full-pipeline

from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([ ("num", num_pipeline, num_attribs), 
                                   ("cat", cat_pipeline, cat_attribs),])

In [11]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Se transforman los datos entrenados - Variables Ind.

X_train = full_pipeline.fit_transform(train_data)
X_train.shape

C:\Users\lPlaneTUFGG\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

(560, 22)

In [12]:
X_train[0,:]

array([ 0.1139584 , -0.88214281,  0.7978327 ,  1.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ])

In [13]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Variable dependiente

y_train = train_data["stroke"]
y_train

379    0
245    1
624    0
57     1
543    0
      ..
402    0
632    0
208    1
552    0
353    0
Name: stroke, Length: 560, dtype: int64

In [14]:
X_test = full_pipeline.transform(test_data) 
X_test

array([[ 3.38418514e-01, -8.35110978e-01, -1.60650538e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.28202560e-01, -4.35725939e-01,  8.37769497e-01, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 3.38418514e-01,  6.78966958e-01, -3.47022278e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-1.59193847e+00,  8.94926488e-05, -6.74646681e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.13958400e-01,  1.80121166e-01, -1.07401469e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.62878629e-01,  1.75067585e+00,  1.67644233e+00, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [15]:
y_test = test_data["stroke"]
y_test

84     1
239    1
283    0
307    0
345    0
      ..
613    0
192    1
498    0
442    0
222    1
Name: stroke, Length: 140, dtype: int64

4. Configurar los hiperparámetros del árbol de decisión de la siguiente manera: criterion=gini, splitter=best,
y random_state=123. Obtener 10 árboles de decisión que resultan de modificar el hiperparámetro
max_depth desde 5 hasta 50 con incrementos de 5.

In [16]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

scores=[]
scor=[]
decision_tree = []
accuracies = []
max_depths = range(5, 51, 5)

for max_depth in max_depths: 
    model_tree = DecisionTreeClassifier(criterion="gini", splitter="best", max_depth=max_depth, random_state=123)
    model_tree.fit(X_train, y_train)
    y_pred = model_tree.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)
    decision_tree.append(model_tree.score(X_test, y_test))
    scores = cross_val_score(model_tree, X_train, y_train, cv=5,scoring='accuracy')
    scor.append(scores.mean())
    
    print("→Puntajes de la validación cruzada:")
    print(scores)
    print(f"→Promedio de los puntajes con max_depth= {max_depth}","->" ,round(scores.mean(),4))
    print("")

best_tree_index = np.argmax(scor)

# Hiperparámetros del árbol con mayor precisión.
print("➤Hiperparámetros del árbol con mayor precisión:")
print("➤max_depth:", max_depths[best_tree_index])
print("➤criterion: gini")
print("➤splitter: best")
print("➤random_state: 123")

→Puntajes de la validación cruzada:
[0.75892857 0.72321429 0.76785714 0.72321429 0.75      ]
→Promedio de los puntajes con max_depth= 5 -> 0.7446

→Puntajes de la validación cruzada:
[0.66964286 0.67857143 0.71428571 0.67857143 0.70535714]
→Promedio de los puntajes con max_depth= 10 -> 0.6893

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 15 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 20 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 25 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 30 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 35 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 40 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 45 -> 0.6911

→Puntajes de la validación cruzada:
[0.625      0.6875     0.75       0.69642857 0.69642857]
→Promedio de los puntajes con max_depth= 50 -> 0.6911

➤Hiperparámetros del árbol con mayor precisión:
➤max_depth: 5
➤criterion: gini
➤splitter: best
➤random_state: 123

5. Incluya en el notebook una tabla con el accuracy para los 10 árboles del punto anterior

In [17]:
import pandas as pd

accuracies_1 = pd.DataFrame({"max_depth": range(5, 51, 5), "accuracy": scor})
display(accuracies_1)

   max_depth  accuracy
0          5  0.744643
1         10  0.689286
2         15  0.691071
3         20  0.691071
4         25  0.691071
5         30  0.691071
6         35  0.691071
7         40  0.691071
8         45  0.691071
9         50  0.691071

6. Repita el mismo procedimiento del punto 4 usando como hiperparámetros criterion=entropy, splitter=best,
random_state=123, y variando el hiperparámetro max_depth desde 5 hasta 50 con incrementos de 5.

In [18]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

scores_2=[]
scor_2 =[]
decision_tree_2 = []
accuracies_p4= []
max_depths = range(5, 51, 5)

for max_depth in max_depths: 
    model_tree_2 = DecisionTreeClassifier(criterion="entropy", splitter="best", max_depth=max_depth, random_state=123)
    model_tree_2.fit(X_train, y_train)
    accuracy_4 = accuracy_score(y_test, y_pred)
    accuracies_p4.append(accuracy_4)
    decision_tree_2.append(model_tree_2.score(X_test, y_test))
    scores_2 = cross_val_score(model_tree_2, X_train, y_train, cv=5,scoring='accuracy')
    scor_2.append(scores_2.mean())

    print("→Puntajes de la validación cruzada:")
    print(scores_2)
    print(f"→Promedio de los puntajes con max_depth={max_depth}","->" ,round(scores_2.mean(),4))
    print("")

best_tree_index_2 = np.argmax(scor_2)

# Hiperparámetros del árbol con mayor precisión.
print("➤Los hiperparámetros del árbol con mayor precisión son:")
print("➤max_depth:", max_depths[best_tree_index_2])
print("➤criterion: entropy")
print("➤splitter: best")
print("➤random_state: 123")

→Puntajes de la validación cruzada:
[0.75892857 0.73214286 0.76785714 0.6875     0.77678571]
→Promedio de los puntajes con max_depth=5 -> 0.7446

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.69642857 0.74107143 0.76785714]
→Promedio de los puntajes con max_depth=10 -> 0.7214

→Puntajes de la validación cruzada:
[0.75892857 0.65178571 0.72321429 0.69642857 0.79464286]
→Promedio de los puntajes con max_depth=15 -> 0.725

→Puntajes de la validación cruzada:
[0.74107143 0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=20 -> 0.7196

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=25 -> 0.7214

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=30 -> 0.7214

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=35 -> 0.7214

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=40 -> 0.7214

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=45 -> 0.7214

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.72321429 0.70535714 0.77678571]
→Promedio de los puntajes con max_depth=50 -> 0.7214

➤Los hiperparámetros del árbol con mayor precisión son:
➤max_depth: 5
➤criterion: entropy
➤splitter: best
➤random_state: 123

In [19]:
from sklearn.metrics import confusion_matrix

# El árbol con la mayor precisión de la simulación
best_tree_2 = DecisionTreeClassifier(criterion="entropy", splitter="best", max_depth=max_depths[best_tree_index_2], random_state=123)
best_tree_2.fit(X_train, y_train)

# Se hace las predicciones para los datos de prueba
y_pred_2 = best_tree_2.predict(X_test)

# Calcular la matriz de confusión
confusion_Punto4 = confusion_matrix(y_test, y_pred_2)

# Imprimir la matriz de confusión
print("Matriz de confusión:")
print(confusion_Punto4)

Matriz de confusión:
[[62 15]
 [26 37]]

7. Incluya en el notebook una tabla con el accuracy para los 10 árboles del punto anterior

In [20]:
import pandas as pd

accuracies_2 = pd.DataFrame({"max_depth": range(5, 51, 5), "accuracy": scor_2})
display(accuracies_2)

   max_depth  accuracy
0          5  0.744643
1         10  0.721429
2         15  0.725000
3         20  0.719643
4         25  0.721429
5         30  0.721429
6         35  0.721429
7         40  0.721429
8         45  0.721429
9         50  0.721429

8. Repita el mismo procedimiento del punto 4 usando como hiperparámetros criterion=entropy, splitter=random, random_state=123, y variando el hiperparámetro max_depth desde 5 hasta 50 con incrementos de 5.

In [21]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

scores_3 = []
scor_3=[]
decision_tree_3 = []

for max_depth in range(5, 51, 5): 
    model_tree_3 = DecisionTreeClassifier(criterion="entropy", splitter="random", max_depth=max_depth, random_state=123)
    model_tree_3.fit(X_train, y_train)
    decision_tree_3.append(model_tree_3.score(X_test, y_test))
    scores_3 = cross_val_score(model_tree_3, X_train, y_train, cv=5,scoring='accuracy')
    scor_3.append(scores_3.mean())

    print("→Puntajes de la validación cruzada:")
    print(scores_3)
    print(f"→Promedio de los puntajes con max_depth={max_depth}","->" ,round(scores_3.mean(),4))
    print("")

best_tree_index_3 = np.argmax(scor_3)

print("➤Los hiperparámetros del árbol con mayor precisión son:")
print("➤max_depth:", max_depths[best_tree_index_3])
print("➤criterion: entropy")
print("➤splitter: random")
print("➤random_state: 123")

→Puntajes de la validación cruzada:
[0.76785714 0.69642857 0.71428571 0.75       0.8125    ]
→Promedio de los puntajes con max_depth=5 -> 0.7482

→Puntajes de la validación cruzada:
[0.66071429 0.69642857 0.66964286 0.73214286 0.71428571]
→Promedio de los puntajes con max_depth=10 -> 0.6946

→Puntajes de la validación cruzada:
[0.69642857 0.67857143 0.66071429 0.75       0.69642857]
→Promedio de los puntajes con max_depth=15 -> 0.6964

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=20 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=25 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=30 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=35 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=40 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=45 -> 0.6911

→Puntajes de la validación cruzada:
[0.69642857 0.73214286 0.61607143 0.70535714 0.70535714]
→Promedio de los puntajes con max_depth=50 -> 0.6911

➤Los hiperparámetros del árbol con mayor precisión son:
➤max_depth: 5
➤criterion: entropy
➤splitter: random
➤random_state: 123

9. Incluya en el notebook una tabla con el accuracy para los 10 árboles del punto anterior.

In [22]:
import pandas as pd
 
accuracies_3 = pd.DataFrame({"max_depth": range(5, 51, 5), "accuracy": scor_3})
display(accuracies_3)

   max_depth  accuracy
0          5  0.748214
1         10  0.694643
2         15  0.696429
3         20  0.691071
4         25  0.691071
5         30  0.691071
6         35  0.691071
7         40  0.691071
8         45  0.691071
9         50  0.691071

10. Indique en el notebook los hiperparámetros que por el momento le permiten obtener el árbol con mayor
accuracy.

In [23]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Comparación de resultados de los puntos 4,6,8

import pandas as pd

df_accuracy_2 = pd.concat([accuracies_1, accuracies_2, accuracies_3], axis=1)
df_accuracy_2.columns = ['max_depth', 'accuracy_p4', 'max_depth', 'accuracy_p6', 'max_depth', 'accuracy_p8']
display(df_accuracy_2)

   max_depth  accuracy_p4  max_depth  accuracy_p6  max_depth  accuracy_p8
0          5     0.744643          5     0.744643          5     0.748214
1         10     0.689286         10     0.721429         10     0.694643
2         15     0.691071         15     0.725000         15     0.696429
3         20     0.691071         20     0.719643         20     0.691071
4         25     0.691071         25     0.721429         25     0.691071
5         30     0.691071         30     0.721429         30     0.691071
6         35     0.691071         35     0.721429         35     0.691071
7         40     0.691071         40     0.721429         40     0.691071
8         45     0.691071         45     0.721429         45     0.691071
9         50     0.691071         50     0.721429         50     0.691071

La anterior tabla nos presenta los valores de los accuracy obtenidos por los árboles de los puntos 4, 6 y 8. Se puede evidenciar un comportamiento en el acuraccy de los árboles del punto 4 con el criterion=gini y splitter=best en donde sus valores son inferiores a los árboles del punto 6 y 8. De igual manera, se nota un comportamiento en el accuracy del punto 8 con criterion=entropy y splitter=random en donde los valores son mucho más altos que los construidos en los puntos 4 y 6.

Así mismo, a continuación, se presentan los árboles con mayor valor de accuracy:

In [24]:
max_value_p4 = round(max(df_accuracy_2["accuracy_p4"]),4)
max_value_p6 = round(max(df_accuracy_2["accuracy_p6"]),4)
max_value_p8 = round(max(df_accuracy_2["accuracy_p8"]),4)

print("➤Mejor valor de accuracy en el punto 4:",max_value_p4)
print("➤Mejor valor de accuracy en el punto 6:",max_value_p6)
print("➤Mejor valor de accuracy en el punto 8:",max_value_p8)

print(" ")
max_accuracy =max([max_value_p4,max_value_p6, max_value_p8])
print("Mejor valor de accuracy en total", max_accuracy)

➤Mejor valor de accuracy en el punto 4: 0.7446
➤Mejor valor de accuracy en el punto 6: 0.7446
➤Mejor valor de accuracy en el punto 8: 0.7482

Mejor valor de accuracy en total 0.7482

In [25]:
best_tree_index_3 = np.argmax(scor_3)
print("➤Los hiperparámetros del árbol con mayor accuracy son:")
print("➤max_depth:", max_depths[best_tree_index_3])
print("➤criterion: entropy")
print("➤splitter: random")
print("➤random_state: 123")

➤Los hiperparámetros del árbol con mayor accuracy son:
➤max_depth: 5
➤criterion: entropy
➤splitter: random
➤random_state: 123

# 11. Seleccione uno de los hiperparámetros disponibles en la documentación (https://scikit learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html) que sea diferente al criterion, splitter, max_depth, y random_state. Realice dos variaciones en el hiperparámetro seleccionado manteniendo los otros hiperparámetros del punto anterior. Indique el accuracy obtenido al modificar el hiperparámetro seleccionado y analice si el árbol de decisión mejora, empeora, o mantiene su exactitud.

In [26]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

accuracies_11=[]
scores_4 = []
scor_4=[]
decision_tree_4 = []

for min_sample_split in range(2, 6, 2): 
    model_tree_4 = DecisionTreeClassifier(criterion="entropy", splitter="best", max_depth=10, random_state=123, min_samples_split=min_sample_split)
    model_tree_4.fit(X_train, y_train)
    decision_tree_4.append(model_tree_4.score(X_test, y_test))
    accuracy_11 = accuracy_score(y_test, y_pred)
    accuracies_11.append(accuracy_11)
    scores_4 = cross_val_score(model_tree_4, X_train, y_train, cv=5,scoring='accuracy')
    scor_4 = scores_4.mean()

    print("→Puntajes de la validación cruzada:")
    print(scores_4)
    print(f"→Promedio de los puntajes con min_sample_split={min_sample_split}","->" ,round(scor_4,4))
    print("")
    
best_tree_index_4 = np.argmax(scor_4)

print("➤Los hiperparámetros del árbol con mayor precisión son:")
print("➤max_depth:", max_depths[best_tree_index_4])
print("➤criterion: entropy")
print("➤splitter: best")
print("➤random_state: 123")

→Puntajes de la validación cruzada:
[0.75       0.65178571 0.69642857 0.74107143 0.76785714]
→Promedio de los puntajes con min_sample_split=2 -> 0.7214

→Puntajes de la validación cruzada:
[0.73214286 0.70535714 0.74107143 0.74107143 0.75892857]
→Promedio de los puntajes con min_sample_split=4 -> 0.7357

➤Los hiperparámetros del árbol con mayor precisión son:
➤max_depth: 5
➤criterion: entropy
➤splitter: best
➤random_state: 123

In [27]:
import pandas as pd

# Accuracy de los 2 arboles construidos
accuracies_11_tree = pd.DataFrame({"min_sample_split": range(2, 6, 2), "accuracy": decision_tree_4})
display(accuracies_11_tree)

   min_sample_split  accuracy
0                 2  0.678571
1                 4  0.692857

In [28]:
#→→→→→→→→→→→→→→→→→→→→→→→→→
# Comparación y conclusión sobre los resultados generados

max_value_p11 = round(max(accuracies_11_tree["accuracy"]),4)
if max_accuracy > max_value_p11:
    print("La precisión disminuyó debido a la red neuronal, por lo tanto, la mejor red tiene un nivel de exactitud de", max_accuracy,
          "que es el resultado del punto 10. Mientras que la nueva red tiene un accuracy de",max_value_p11)
elif max_accuracy < max_value_p11:
    print("La red neuronal mejoró la exactitud, por lo que la mejor red tiene un accuracy de", max_value_p11, 
          "que es el resultado del punto 11. Mientras la red del punto anterior tiene un accuracy de",max_accuracy )
else:
    print("A pesar de las variaciones en los hiperparámetros, la red neuronal logró mantener su nivel de exactitud, ya que los valores de precisión se mantuvieron constantes.")

La precisión disminuyó debido a la red neuronal, por lo tanto, la mejor red tiene un nivel de exactitud de 0.7482 que es el resultado del punto 10.Mientras que la nueva red tiene un accuracy de 0.6929